apiVersion: v1
kind: ConfigMap
metadata:
  name: pingup-config
  namespace: pingup
data:
  # MongoDB Configuration
  MONGODB_URI: "mongodb+srv://nguyentuancanh305:Canh3005@cluster0.0bqq5.mongodb.net"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Server Configuration
  NODE_ENV: "production"
  PORT: "3000"
  FE_URL: "http://localhost:5000"
  
  # Client Configuration (API URL)
  VITE_API_URL: "http://localhost:3000/api"
  # VITE_SOCKET_URL: "http://localhost:3000"