apiVersion: v1
kind: ConfigMap
metadata:
  name: pingup-config
  namespace: pingup
data:
  # MongoDB Configuration
  MONGO_URI: "mongodb://mongodb:27017/pingup"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Server Configuration
  NODE_ENV: "production"
  PORT: "5000"
  
  # Client Configuration (API URL)
  VITE_API_URL: "http://localhost:5000"
  VITE_SOCKET_URL: "http://localhost:5000"
